feat: 예약 API 테스트 케이스 추가 및 수정(#66)
goorm-debug-alss/petclinic pull request #67
Opened 2024-12-21 10:25 UTC by Do-oya

### 중요 변경 사항 🚨

> 하기 사항이 변경된 경우 체크해주세요.

- [ ] DB 스키마가 수정되었습니다.
- [ ] 환경변수 파일이 추가/삭제/수정되었습니다.

### 작업 내용 🧑🏻‍💻

> 기능 추가, 버그 수정 등 작업 내용을 작성해주세요.

- 리뷰 조회, 생성 서비스 예외처리 구현
- 테스트 케이스 추가

### 관련 이슈

> 본 PR이 머지되면 자동으로 닫을 이슈를 [형식](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)에 따라 작성하고,
> 종료하지 않고 연결만 한다면 예약어 없이 작성해주세요.

- close #66

2024-12-21 11:22 UTC, leedidu commented on src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewCreateService.java
리뷰 생성하면 해당 수의사 평점이랑 리뷰개수가 업데이트 되는 코드도 있어야할 것 같아요.ᐟ.ᐟ

2024-12-21 11:24 UTC, leedidu requested changes
수의사 평점이랑 리뷰개수 업데이트만 추가해주세용 ~~
주말에도 고생이 많으심니당..

2024-12-21 13:06 UTC, Do-oya commented on src/main/java/org/springframework/samples/petclinic/domain/review/service/ReviewCreateService.java
넵~!!

2024-12-21 13:52 UTC, Do-oya commented
추가했습니다! 👽

2024-12-22 09:08 UTC, leedidu approved these changes
굳이에용👍

2024-12-22 10:06 UTC, junhwan98 approved these changes
좋습니다 !! 👍🫶

2024-12-22 14:22 UTC, merged